# Generated by Django 6.0.7 on 2026-08-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_isbn13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
